### PR TITLE
Create US-map-Visulization-using-D3.md

### PR DESCRIPTION
**Pull request by AakanxuShah**
Created a new article for Data visualization project . Issue #541 .

### CODE REVIEW

**Comment by AakanxuShah** [comment]
Please take a look at it and feel free to let me know if anythings needs to be changed or improved.

**Comment by Rafase282** [comment]
I see a few things, would yuo want me to point them out or merge and take care of it?

**Comment by AakanxuShah** [comment]
If they are minor changes, then go ahead, merge it and make the changes. 
Else let me know. I have got all the time in the world to make the changes !  👍 
Whichever's convenient for you .

**Comment by Rafase282** [comment]
1. Link this and the other D3 challenge in the map.
2. Make sure to add a new line after each heading.
3. For list use `-` instead of that circle there.

**Comment by Rafase282** [comment]
I just noticed that this does not seem to be a d3 project but still very useful.

**Pull request merged**
