### PR TITLE
Revert "Temporarily add Found-a-Bug article back"

### PR DESCRIPTION
**Pull request by raisedadead**
Reverts FreeCodeCamp/wiki#970
Reason FreeCodeCamp/FreeCodeCamp#8679 is in production.

Thanks for the fallback @Rafase282 and @abhisekp 
I am yet to change the links in the issues, but that is trivial (I will take care of that) and this may be merged.

### CODE REVIEW

**Comment by Rafase282** [comment]
Thanks

**Comment by raisedadead** [comment]
Fastest PR merge ever!

**Comment by Rafase282** [comment]
What links did you need to change?

**Comment by raisedadead** [comment]
Nothing I just need to update the links in the main repo's issues threads, but that's not very important.
So this can be considered, complete.

**Pull request merged**
