### PR TITLE
Update Algorithm-Caesars-Cipher.md

### PR DESCRIPTION
**Pull request by anuragaryan**
There was a mistake in my code regarding the ASCII range, rectified it in both the solutions. 
Thanks to @mauney from gitter.im for pointing it out.

### CODE REVIEW

**Comment by Rafase282** [comment]
@anuragaryan Would you mind explaining it to me then? I tested the code and my code works, I don't know if you based your solution off mine or why did you also use 91 but I had a good reason for it when I did.

Both code still work prior to these changes.

**Comment by anuragaryan** [comment]
@Rafase282 A-Z is 65-90 in ASCII. As per initial condition, it checks for ASCII>91, thus consider ASCII 91 i.e.'[' as an English Alphabet and shift it 13 places backward. Which shouldn't happen.

**Comment by Rafase282** [comment]
@anuragaryan sorry I got confused with the code, I didn't submit my answer to that one, mine is:

```js
function rot13(str) { // LBH QVQ VG!
  return str.toUpperCase().split('').map(function(subStr) {
    return decode(subStr.charCodeAt(0));
  }).join('');

  function decode(arg) {
    // Takes care of characters that are not in [A-Z] such as ! and ? and decodes [A-Z]
    var decoded = 0;
    if (arg < 65 || arg > 90) {
      return String.fromCharCode(arg);
    } else {
      decoded = (arg + 13) % 91;
    }
    return String.fromCharCode(decoded < 65 ? decoded += 65 : decoded);
  }

}
// Change the inputs below to test
rot13("SERR CVMMN!");
```

It works and the 91 is needed because of the way I went about with 90 it would go and give me 0 instead of 1 and mess things up.

**Comment by anuragaryan** [comment]
I happens. :+1:

**Pull request merged**
