### PR TITLE
Added two shorter solutions for Bonfire missing letters and fixed some wiki formatting

### PR DESCRIPTION
**Pull request by sabahang**
Added two shorter solutions and fixed some styling issues

### CODE REVIEW

**Comment by SaintPeter** [comment]
Please set a more descriptive PR name.

**Comment by sabahang** [comment]
What do you mean by PR?

**Comment by SaintPeter** [comment]
PR = Pull Request = This thing we're comment on.  You can click "edit" up at the top of the interface and change the title of the PR.
image

In general, it should be more descriptive of the contents like:
Add additional solutions to Bonfire: Blah Blah

**Comment by sabahang** [comment]
Thanks for explanation! done and done! hope it's good enough now, I try to deter from long titles but I guess sometimes end up sacrificing clarity

**Comment by SaintPeter** [comment]
You don't need to be QUITE that detailed.  Just broad strokes, like my example.  Regardless, this is good.  :+1:

**Pull request merged**
