### PR TITLE
Added a check to see if "tracks" exists for the given element of the …

### PR DESCRIPTION
**Pull request by DarrenJansen**
…array.

The existing solution does not allow the camper to pass the challenge. I'm a beginner and am having trouble with JSON more than anything else, so there may be some mistakes in the way I did things. However, this solution that I put here let me pass the challenge, whereas the existing solution did not.

### CODE REVIEW

**Comment by Rafase282** [comment]
@DarrenJansen thanks for the update. Would you mind adding some updates to the format?

Please see #1094 and apply those changes. It is mostly copy paste.

**Comment by DarrenJansen** [comment]
@Rafase282 How does this look? I think the format is now in line with the wiki template.

**Comment by Rafase282** [comment]
@DarrenJansen it looks great, it is only missing the repl.it snippet. Do you know how to add it?

**Comment by DarrenJansen** [comment]
Hi @Rafase282 Sorry, I'm not sure. Should I just paste that code in somewhere? Where? Thanks.

**Comment by Rafase282** [comment]
I updated the template to reflect this, you still need to save the code on
relp.it and provide the right URL. You would paste it after the code in the
wiki.

On Mon, Jun 13, 2016, 12:20 AM Darren Jansen <notifications@github.com>
wrote:

> Hi @Rafase282 <https://github.com/Rafase282> Sorry, I'm not sure. Should
> I just paste that code in somewhere? Where? Thanks.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/wiki/pull/1108#issuecomment-225486483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AARZ0mr-bzDxcnQ6CJSEYm6MNa9Jvmapks5qLNp6gaJpZM4Iyl9g>
> .
>
-- 
Kind Regards,

Rafael Rodríguez
Junior Web Developer
https://rafase282.github.io/

**Comment by Rafase282** [comment]
Please fix the conflicts. Let me know in the chat if you need help.

**Comment by DarrenJansen** [comment]
I added the Repl.it snippet. Would you mind checking to see if the code operates correctly?

**Comment by DarrenJansen** [comment]
This is the chat, right? Or do you mean gitter? Sorry, Newbie here. What are the conflicts?

**Comment by Rafase282** [comment]
The chat, I don't know. You will have to check with git to see where the conflict is, and yes, gitter for the wiki chat.

**Comment by DarrenJansen** [comment]
Oh, Ok. I understand. There is a merge conflict. I'll figure out how to resolve conflicts. I'm kinda basic with Git, so it might take me a couple days . . . :-)

**Comment by Rafase282** [comment]
If you use atom you can install a plugin for it. Also you could just sync your fork on the master and then rebase on your branch or start over.

**Comment by Rafase282** [comment]
I fixed the issues and update the template implementation on #1148 

Thanks @DarrenJansen

**Pull request closed without merging**
