### PR TITLE
JS Strict Mode

### PR DESCRIPTION
**Pull request by rishipuri**
New wiki content w.r.t #367 

Please review and lemme know if any changes needed. 

Thank you.

### CODE REVIEW

**Comment by Rafase282** [comment]
Looks good to me overall.

**Comment by abhisekp** [comment]
:+1:

**Comment by Rafase282** [comment]
@rishipuri let me know if you want to implement that or if you prefer I merge now.

**Comment by rishipuri** [comment]
@Rafase282 Should be good to merge.

**Pull request merged**
