### PR TITLE
docs(missing-letter): yet another implementation

### PR DESCRIPTION
**Pull request by sarbbottam**
probably the shortest

### CODE REVIEW

**Comment by Rafase282** [comment]
Please read [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki#contributing-to-the-wiki) section.

**Comment by sarbbottam** [comment]
I have read the [Contributing to the Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki#contributing-to-the-wiki) section, but could not comprehend the reason for closing the PR. Could you please be precise?

**Comment by Rafase282** [comment]
>Algorithm articles that do not use this template will be removed. Please note that while we will publish solutions that can help others, we don't need many of them and a maximum of three solutions will be accepted in the following categories:

>Basic
Intermediate
Advance

Basically we don't want more than 3 solutions and for new solutions we need the new template implemented.

**Comment by sarbbottam** [comment]
Thanks! I have been wondering whats wrong with my algorithm!

>Basically we don't want more than 3 solutions and for new solutions we need the new template implemented.

Gotcha!! BTW, **this wiki page already had more than three solutions**!

Since this is algorithm, you might want to take a look at the implementation, if its worth replacing any existing one, if your are strict on  **3 solution only rules**.

**Comment by Rafase282** [comment]
@sarbbottam they are the old ones. We haven't update all algorithms to have this new template. If you wish, it would be great if you help us do this by updating as many as you want after #890 gets merged.

**Comment by sarbbottam** [comment]
Sounds good! While editing this wiki, It looked odd to have multiple `H1`. 
Do have any roadmap or checklist to keep track and avoid multiple efforts (more than one guy working on the same file for same purpose)?

**Comment by Rafase282** [comment]
What do you mean by `h1`?

We have the issues and chats. When we have an open issue, anyone can work on it, they just have to let us know. Another way is to check for current pull requests before opening yours.

**Comment by sarbbottam** [comment]
> What do you mean by `h1`?

[`# heading level1`](http://commonmark.org/help/tutorial/04-headings.html)

There are three `h1`s in this document.

[`# Problem Explanation:`](https://github.com/FreeCodeCamp/wiki/blame/master/Algorithm-Missing-letters.md#L1)
[`# Code Explanation:`](https://github.com/FreeCodeCamp/wiki/blame/master/Algorithm-Missing-letters.md#L150)
[`# Credits:`](https://github.com/FreeCodeCamp/wiki/blame/master/Algorithm-Missing-letters.md#L171)


---

Ideally there should have been only one `h1`, `# Algorithm - Missing letters` or something similar.
And rest `heading` would follow the standard hierarchy.

Although [html5 does not restrict multiple `h1` in a document](http://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824), I have not seen `markdown`s using multiple `h1` in a document.

**Comment by Rafase282** [comment]
The [template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution) fixes this.

The file has two because the first is for the articel and the second is part of the template.

**Comment by sarbbottam** [comment]
> The file has two because the first is for the articel and the second is part of the template.

Which file are you referring to?

Multiple `h1`s are w.r.t. https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Missing-letters.md and not the [template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution).

Then again, how do I see and copy the `markdown` of the [template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution). I could only see it in rendered form.

**Comment by Rafase282** [comment]
You can fork and edit the files or if you have to do it via web you can click on the raw to view the markdown.

**Comment by sarbbottam** [comment]
Sorry, I don't follow you.

The [template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution) is part of the wiki and Wiki is not part of the fork, without edit access there is no way to see the markdown content.
 
However, in the wiki, you can use ```` ``` md ````   to render it as `markdown`, so that, non members can copy the code and use it.

**Comment by Rafase282** [comment]
You can use the material from the fork to check the raw. Anyways, here it is [raw template](https://raw.githubusercontent.com/FreeCodeCamp/wiki/master/Wiki-Template-Challenge-Solution.md).

**Comment by abhisekp** [comment]
@sarbbottam 
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by sarbbottam** [comment]
Broken link - How To Contribute To The Wiki at [CONTRIBUTING](https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md)

**Comment by sarbbottam** [comment]
I guess all the links are broken at [CONTRIBUTING](https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md)

**Comment by Rafase282** [comment]
I have fixed those links on a new PR, thanks.

**Comment by abhisekp** [comment]
@sarbbottam you may access the CONTRIBUTING guidelines from https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/CONTRIBUTING

**Pull request closed without merging**
