### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by studenton**

### CODE REVIEW

**Comment by studenton** [comment]
@Rafase282 Why wasn't it merged? Can I know?

**Comment by Rafase282** [comment]
Yes, see here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9513#issuecomment-230159736

**Comment by Rafase282** [comment]
In this particular case, the links are meant to be relative and the way they are. they will not work if you click them in this forum but they will work if you click them on the react wiki or the github one as intended.

If you want to help with links I recommend you take a look a this issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9513#issuecomment-230159736

**Comment by studenton** [comment]
Got it. Thanks for explaining.

**Pull request closed without merging**
