### PR TITLE
Split Article Python More Built-in Types

### PR DESCRIPTION
**Pull request by Rafase282**
Split the articles, many needs more information, I added some to the main article and some links on others that needed it.

### CODE REVIEW

**Comment by theflametrooper** [comment]
## LGTM :+1:

**Comment by alayek** [comment]
# LGTM :+1: 

@koustuvsinha please take a look.

**Comment by koustuvsinha** [comment]
Needs contextual headers as mentioned in #810 for each article

**Comment by Rafase282** [comment]
Added headers and second heading on long articles.

**Comment by koustuvsinha** [comment]
# LGTM :thumbs_up:

**Pull request merged**
