### PR TITLE
Create accessibility 101

### PR DESCRIPTION
**Pull request by zersiax**
This is the first article I proposed in December in the Curriculum development gitter channel. Kindly look it over and see if it can be integrated into the wiki somewhere.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Couple of things: 
1.  You should file this against the Wiki repo: [FreeCodeCamp/wiki](https://github.com/FreeCodeCamp/wiki)
2. You should name the file `Accessibility-Introduction.md`
3. Your Markdown is not right - you need spaces after your `###` header markers
4. Even if this was the right repo, you've filed this against the `master` branch, which is a bozo no-no

Here is a [Detailed Guide on How to Contribute to the Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Contribute-To-The-Wiki)

The wiki is definitely the place for this.  Once you have a PR opened against that I'll do a more significant edit of the article itself.

Thanks!

**Comment by SaintPeter** [comment]
Can you rename the file, though? Otherwise I cannot read it as Markdown.

**Comment by zersiax** [comment]
I followed the first link on the wiki's main page. It was a little
weird as I wasn't given an actual fork, but rather got in this
interface where I can edit a file right in the web interface. I have a
markdown file right here, but good thinking on the headings. I'll
validate, then re-request to the right repo. Close this one?


2016-01-16 20:35 GMT+01:00, Rex Schrader <notifications@github.com>:

**Comment by SaintPeter** [comment]
Sure, that's fine.  You can also rename the branch to be more meaningful.

**Pull request closed without merging**
