### PR TITLE
Rename Spanish Home.md to ES-Home.md

### PR DESCRIPTION
**Pull request by Rafase282**
Fix for #721

### CODE REVIEW

**Comment by theflametrooper** [comment]
## LGTM :+1:

**Comment by Rafase282** [comment]
I'm making a PR per language just in case.

**Comment by alayek** [comment]
# LGTM  :+1:

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @Rafase282 .

**Pull request merged**
