### PR TITLE
Known-Issue-With-Codepen.md

### PR DESCRIPTION
**Pull request by micahbales**
I spent about a week trying to debug a problem that ended up being an issue with a Chrome extension conflicting with Codepen. This file is meant to provide a list of known issues with Codepen, to reduce frustration in the future.

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Please change it in a proper Markdown file (ending with .md)

**Comment by micahbales** [comment]
I changed the file name to include the .md suffix, and corrected an error in the markup. Hopefully this resolves the issue. Thanks!

**Comment by koustuvsinha** [comment]
Few more changes : 

* Add a page header
* Rename file using Camel Case format : Known-Issues-With-Codepen.md
* Squash the commits

**Comment by Rafase282** [comment]
@micahbales Do you plan on adding more issues soon? There is currently only one issue listed which is okay, but then you should change the article to be in singular until more issues are added.

**Comment by micahbales** [comment]
Sorry, this is my first time using GitHub. I'm trying to figure out how to squash (rebase?) the revisions. Just downloaded local client...

**Comment by Rafase282** [comment]
It's alright, just make sure you rename the filename to `Known-Issue-With-Codepen.md` If you need help squashing let us knwo ont eh wiki room.

**Comment by QuincyLarson** [comment]
@micahbales Thanks for contributing to our wiki. This is a great idea, and we've needed a CodePen issues article for some time :)

One thing we could mention is that CodePen overrides `<a href='URL'>` anchor elements, which means that you have to add a `target='_blank'` to your anchor elements - otherwise they won't work.

**Comment by micahbales** [comment]
Thanks, @QuincyLarson. This is a good introduction to GitHub!

I still haven't been able to figure out how to squash my numerous and sloppy edits. When I search for solutions, I'm mostly pointed to the CLI, which I'm not super familiar with quite yet. Any ideas of how to accomplish this in the GUI/desktop client?

Thanks!

**Comment by abhisekp** [comment]
@micahbales don't worry about squashing commits. We can do that for you. Just keep adding awesome articles. :smiley:  

Also you might want to add the issue related to http://imgur.com image hotlinking which doesn't work sometimes because of their ToS. 

Alternative to imgur might be http://postimg.org

**Comment by Rafase282** [comment]
@micahbales Please Check https://github.com/micahbales/wiki/pull/1 either merge or please make that change.

**Comment by raisedadead** [comment]
@Rafase282 this one just needs squashing, I believe all other changes have been done right?

**Comment by Rafase282** [comment]
I'll take care of it @raisedadead

**Pull request closed without merging**
