### PR TITLE
Adds eslint and lint according to FCC config

### LINKED ISSUE #343: Lint According to FCC ESlint config
Since changes here get pulled into the camperbot submodule I noticed quite a few linting errors in the scripts.

### PR DESCRIPTION
**Pull request by Rafase282**
Closes #343

### CODE REVIEW

**Comment by Rafase282** [comment]
Anybody? @FreeCodeCamp/wiki-mods

**Comment by raisedadead** [comment]
I would love to help and QA this @Rafase282 , but how do I test it?

**Comment by Rafase282** [comment]
@raisedadead just install eslint and check the files using the FCC config file, I attached those. No need to run the scripts, I personally didn't but @ltegman requested this to be done.

**Comment by ltegman** [comment]
The FCC codebase uses 2 space indents rather than 4 spaces.

**Comment by Rafase282** [comment]
I used the configuration file and followed the recommendation it told me. Did you take a look at the configuration file I added? Did I use the wrong one? @ltegman

**Comment by ltegman** [comment]
For reasons I'm not sure of the .eslintrc doesn't have any indentations rules, it's just the way the whole codebase is. For consistency sake this should follow that.

**Comment by Rafase282** [comment]
@ltegman sorry for the delay, I have changed the spaces.I also added an extra file from my wn projects that takes care of the indentation.

Whoever gets to merge this can squash or merge as is.

**Comment by abhisekp** [comment]
@Rafase282 There are some errors you might wanna fix
```sh
▶ node_modules/.bin/eslint -c .eslintrc .             

/media/Xtras/GitRepos/FreeCodeCamp.wiki/scripts/convert_files.js
  19:38  error  Unexpected space before function parentheses  space-before-function-paren
  23:41  error  Unexpected space before function parentheses  space-before-function-paren
  26:18  error  Unexpected space before function parentheses  space-before-function-paren
  36:28  error  Unexpected space before function parentheses  space-before-function-paren

/media/Xtras/GitRepos/FreeCodeCamp.wiki/scripts/create_structure.js
  13:27  error  Unexpected space before function parentheses  space-before-function-paren
  17:39  error  Unexpected space before function parentheses  space-before-function-paren
  19:18  error  Unexpected space before function parentheses  space-before-function-paren
  29:28  error  Unexpected space before function parentheses  space-before-function-paren
  31:52  error  Unexpected space before function parentheses  space-before-function-paren

✖ 9 problems (9 errors, 0 warnings)

```

**Comment by Rafase282** [comment]
@abhisekp maybe that is from the new file. I will take a look, after all it is supposed to follow the FCC's configuration.

**Comment by Rafase282** [comment]
I checked and the only errors I got was the line endings, I requested unix and i'm on windows right now, other than that no issues

**Comment by Rafase282** [comment]
@abhisekp I ran the command you posted and saw the issue. I used c9 to beautify with the right space but it changed something else and I didn't notice. So I changed it back on atom and changed the beautify config on atom. tested, squashed.

Also removed the line ending checks, so we can run from windows or linux.

**Comment by abhisekp** [comment]
# :+1: LGTM

_Merging in 5 minutes_

**Pull request merged**
