### PR TITLE
Add REPL snippets to JS Intermediate Algorithm Challenges

### PR DESCRIPTION
**Pull request by alayek**
refers to intermediate algorithm section in #836

### CODE REVIEW

**Comment by alayek** [comment]
@theflametrooper @koustuvsinha @Rafase282 @abhisekp please take a look. There were some minor issues with code, I have fixed it wherever possible.

**Comment by koustuvsinha** [comment]
amazing work @alayek !!

**Comment by abhisekp** [comment]
@alayek wow! so many .... awesome! It will really benefit everyone

What's your opinion on these?

<kbd><a href="https://repl.it/CJZa/0"> <strong>REPL it!</strong> :rocket: </a></kbd> <kbd><a href="http://jsbin.com"> <strong>JSBin Demo</strong> :rocket: </a></kbd>

**Comment by alayek** [comment]
@abhisekp the one without blue links. The second one.

**Comment by theflametrooper** [comment]
Great work, thanks @akayek :shipit:

**Pull request merged**
