### PR TITLE
Recreate article about online and offline IDEs

### PR DESCRIPTION
**Pull request by Rafase282**

### CODE REVIEW

**Comment by alayek** [comment]
My problem with this article has always been the way we are tossing around non-standard terms like "Online IDE" and "Offline IDE". Either they should be defined in the beginning of the articles, or when the terms first appear, link to some external free public resources which explain them properly.

I am not even sure about the differences between these two, and this is the first time I am hearing about these two terms.

**Comment by Rafase282** [comment]
I'm hoping the original author will pick it up. But after editing the article I think it is missing more online ide, perhaps c9 could be added.

As for explaining what an IDE is I guess that could be also added.

**Comment by theflametrooper** [comment]
I'm guessing there's going to be a separate article about text editors? If so, i'd love to help.

**Comment by alayek** [comment]
@theflametrooper sure. Why not you write a draft and have it reviewed. If you want to raise a PR - you can do that too.

**Comment by theflametrooper** [comment]
@alayek Is there an article about creating an article? lol

**Comment by alayek** [comment]
@theflametrooper You can start with [this](https://medium.freecodecamp.com/how-to-land-your-first-open-source-contribution-from-your-browser-in-15-minutes-756d9bbf81ad#.x38yqjr02) or [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Contribute-To-The-Wiki).

**Comment by abhisekp** [comment]
This PR addressed the issue in https://github.com/FreeCodeCamp/wiki/issues/598

**Pull request closed without merging**
