### PR TITLE
Adding Ruby introduction

### PR DESCRIPTION
**Pull request by Sayanc93**

### CODE REVIEW

**Comment by Rafase282** [comment]
You can do ```ruby for syntax highlight.

**Comment by Rafase282** [comment]
Other than that it looks good

**Comment by Sayanc93** [comment]
@Rafase282 - Hey thanks for the suggestion, but I was trying to be consistent with Python introduction...it followed the same pattern, should i change it to ``` or let it be?

**Comment by raisedadead** [comment]
@Sayanc93 What @Rafase282 Meant is since the code snippets are in ruby you need to add them as:


\`\`\`ruby
your code here...
\`\`\`

**Pull request merged**
