### PR TITLE
Add Campsite JSON File

### PR DESCRIPTION
**Pull request by LibertysYarn**

### CODE REVIEW

**Comment by raisedadead** [comment]
@LibertysYarn Thanks for the PR, I am editing the PR title, we should not include any issue no.s in the commit message or the PR titles.

Adding @hallaathrad for QA.

**Comment by Rafase282** [comment]
It's been over a week. What's the status on this? is it useful? should it be merged? closed?

**Comment by abhisekp** [comment]
Would be nice to add latitude and longitude info instead of null (*optional*)

**Comment by samosale** [comment]
Have a list with all cities(950) - 750 have coordinates, but some are incorect(due to same names of different cities ex. Moscow Russia vs Moscow Usa ) 
https://github.com/samosale/fccCities/blob/master/fccCitiesFull.json

One should fetch data from here https://developers.google.com/maps/documentation/geocoding/intro?csw=1#BYB

Example https://maps.googleapis.com/maps/api/geocode/json?address=Jyv%C3%A4skyl%C3%A4,+Finland

**Comment by hallaathrad** [comment]
So how would y'all say we proceed about this?

**Comment by samosale** [comment]
I will fetch coords from google api just to grab some time.

**Comment by alayek** [comment]
It's been 16 days of inactivity on this PR. What to do here?

@Rafase282 @raisedadead please take a look.

**Comment by Rafase282** [comment]
Feel free to re-open when there is something new.

**Pull request closed without merging**
