### PR TITLE
Fifth solution

### PR DESCRIPTION
**Pull request by benschac**

### CODE REVIEW

**Comment by benschac** [comment]
cc: @mlm603 -- What do you think of the solution I added?

**Comment by abhisekp** [comment]
> ----
This PR is <kbd><b>blocked</b></kbd> till the new [**`Challenge Solution Template`**](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Solution-Template) is implemented in the original file.

> @benschac you'll be notified once the solution has been updated to the new format.

> <p align="center">Read <a href="https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Guide-Online-Contribution"><b>Contributing Guidelines</b></a><br>Chat with us in <kbd><a href="#"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by benschac** [comment]
Fair enough.  The new template looks good.

**Comment by Rafase282** [comment]
I'm closing this, it can be reopened when we are reading to review new solutions, and in such case many changes might be needed. I'm planning on creating an article on how to contribute to these particular articles.

**Comment by benschac** [comment]
Moving forward should I still create pull requests for the wiki? Is each
and every wiki page going to need to be manually updated with the new
markdown template + content?

We're should we post solutions in the mean time if there isn't a solution
in the wiki?

On Wed, Mar 16, 2016 at 4:27 PM, Rafael J. Rodriguez <
notifications@github.com> wrote:

> I'm closing this, it can be reopened when we are reading to review new
> solutions, and in such case many changes might be needed. I'm planning on
> creating an article on how to contribute to these particular articles.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/wiki/pull/582#issuecomment-197533323>
>



-- 
*Benjamin Schachter*
Project Manager
bschachter@dramafever.com
<https://www.dramafever.com/>

**Comment by abhisekp** [comment]
@benschac come chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"> <b>FreeCodeCamp/Wiki</b></a></kbd>

**Comment by Rafase282** [comment]
@benschac This is for all algorithm articles. The wiki has many other interesting articles you could contribute to, feel free to check the issues onthe repo also. If you are focuses on challenges only then youa re welcome to create articles for the advance projects in data visualizatiion, react, and backend. No solution code but tips, observations and overall information to help fellow campers solve the challenge. Algorithms are the only ones we allow for explicit solutions to be posted and we are closing them to restructure using the new template and limiting the solutions because if you need more than three ways to solve a problem then you are approaching it the wrong way and no amount of solutions will help you learn it. Instead my aim is to keep it simple and a solution for each degree of camper, beginner, intermediate and advanced.

As @abhisekp feel free to come to the chat and we can discuss further.

**Pull request closed without merging**
