### PR TITLE
Articles Starting with T: Rename filenames, add titles

### PR DESCRIPTION
**Pull request by Rafase282**
Refers to #889

### CODE REVIEW

**Comment by abhisekp** [comment]
The return early pattern is not limited to JS. It's a pattern which is applicable for all types of programming paradigms and languages.

**Comment by Rafase282** [comment]
@abhisekp fixed.

**Comment by abhisekp** [comment]
@Rafase282 `Translation-Translate.md` doesn't look right

**Comment by Rafase282** [comment]
Suggestions?

**Comment by abhisekp** [comment]
@Rafase282 
**File Rename** (typo)

```diff
- Tranlstaion-Create-Issues.md
+ Translation-Create-Issues.md
```

**File Rename:-** (singular vs plural)

```diff
- Translations-Guide.md
+ Translation-Guide.md
```

**Comment by abhisekp** [comment]
# :+1: LGTM

**Pull request merged**
