### PR TITLE
Save time at the register with Python and Monary.guide

### PR DESCRIPTION
**Pull request by escapethebadjob**
For WALMART or OuterWall

### CODE REVIEW

**Comment by Rafase282** [comment]
Hello,

Thanks for the contribution. However there are a few things to do. Please write as a guide, use third person not first, the filename needs to change. Please refer to the guidelines for more details.

**Comment by escapethebadjob** [comment]
Hello,

And thank you Sir, for you professionalism in noting my mistakes.  That is the kind of stuff that will certainly keep people engaged with and continuing to come back trying to learn to do things the right way!

Truly appreciate that!  Is there some definitive video which may have helped me to avoid this mistake?

**Comment by Rafase282** [comment]
@escapethebadjob currently there is no video guide only text.

- [Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/CONTRIBUTING)
- [The guide section](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki#guides-on-how-to-contribute) from the wiki home.

**Comment by Rafase282** [comment]
@escapethebadjob feel free to reopen the PR when you have time. You can also get help in our wiki chat room. For now I will close this PR.

**Pull request closed without merging**
