### PR TITLE
Undo git add article

### PR DESCRIPTION
**Pull request by aaronTHJ**
Article to undo ```git add``` before committing.

### CODE REVIEW

**Comment by Rafase282** [comment]
If you are doing inline code then you just need one backtick *`*

**Comment by awesomeaniruddh** [comment]
This is a useful topic, but does it merit its own article?

**Comment by Rafase282** [comment]
Also, filename should be `Git-Undo-Add.md`

**Comment by awesomeaniruddh** [comment]
I just checked and we do have a very similar (although not exactly the same) article: https://www.freecodecamp.com/wiki/en/git-undo-redo-a-commit/

I think we can probably modify that article slightly @Rafase282?

**Comment by Rafase282** [comment]
@awesomeaniruddh what do you suggest?

**Comment by awesomeaniruddh** [comment]
@Rafase282 
I don't know really. The topic content itself is really useful and should be added to the wiki, but it's too small to be its own article in my opinion?

Modifying the article I linked to be more general and about both commits and staged files makes the most sense to me.

**Comment by alayek** [comment]
@awesomeaniruddh what's the standard minimum size (in terms of line no. or word count) for a wiki article?

**Comment by Rafase282** [comment]
Well originally according to [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Style-Guide) 

>Keep your wiki articles short and focused.

**Comment by awesomeaniruddh** [comment]
Yeah well, it's just that I thought that this article was *too short*

**Comment by abhisekp** [comment]
I don't think is anything difficult or tricky thing in git to do. And as @awesomeaniruddh says the article is *too short* to add. So it's better to add in other article.

**Comment by alayek** [comment]
I was thinking maybe we add this with the git add article, instead of creating another standalone article.

**Comment by Rafase282** [comment]
https://github.com/aaronTHJ/wiki/pull/2
https://github.com/aaronTHJ/wiki/pull/1

**Pull request merged**
