### PR TITLE
Git-shortcut.md

### PR DESCRIPTION
**Pull request by aj07**
kindly add this anf it will be upgraded soon

### CODE REVIEW

**Comment by Rafase282** [comment]
Please only use markdown.

**Comment by hallaathrad** [comment]
See https://github.com/FreeCodeCamp/wiki/pull/525 for further corrections.

**Comment by aj07** [comment]
What is markdown?

On Sun, Mar 6, 2016 at 9:23 PM, Justin Richardsson <notifications@github.com

**Comment by hallaathrad** [comment]
@aj07 http://bfy.tw/4c0Y
It's the way we format articles here at the wiki. 
Alternatively, you can review the multiple links @Rafase282 has given you to https://guides.github.com/features/mastering-markdown/

cheers :+1:

**Pull request closed without merging**
