### PR TITLE
Challenge: Logical Order in If Else Statements.md

### PR DESCRIPTION
**Pull request by tstusr441**
Category: Basic Javascript
Challenge Number: 69
Challenge Name: **Challenge: Logical Order in If Else Statements**

There's currently no wiki page for this particular challenge.

### CODE REVIEW

**Comment by raisedadead** [comment]
@tstusr441 Thanks for the PR.

Please change the file name as per our [Pull Request Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/PULL_REQUEST_TEMPLATE).

**Comment by tstusr441** [comment]
Thank you for your response @raisedadead .
I have changed the file name to be in accordance with the Pull Request Guidelines.

**Comment by raisedadead** [comment]
Thanks for the changes @tstusr441 :+1:!
This looks good to me.
 
You just have to [squash the commits](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) and we are good to merge!

**Comment by Rafase282** [comment]
@tstusr441 Please change the information so that you are not directly providing the answer that they can copy paste. For these more text explanation and similar code example to the ones provide in its explanation is desired.

**Comment by Rafase282** [comment]
When you are ready to make the changes feel free to contact me to reopen this.

**Pull request closed without merging**
