### PR TITLE
Update where do I belong

### PR DESCRIPTION
**Pull request by alayek**
Refer #1094

### CODE REVIEW

**Comment by Rafase282** [comment]
It is only missing links on the solution's sections.

**Comment by Rafase282** [comment]
Please add links to functions that are used on the solutions.

**Comment by Rafase282** [comment]
I was working on this and I came up with a shorter version of the second solution but decided that it was wrong because the challenge ask us to find the index after we sort from smaller to larger where the number would go, but it does not ask us to actually insert it so technically the second solution is wrong.

Please remove it and remove the second name. You can add this one:

```js
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  function minToMax(arr){
    return arr.sort((curr,next)=>curr>next);
  }
  var index = minToMax(arr)  
    .findIndex(function(n){
      return num <= n;
    });
  return index === -1? arr.length : index;
}

getIndexToIns([40, 60], 500);
```

I'm still working on refining it but while I could make it to stand a fewer lines, I think modulizing it like this is more future proof in real life than cramming all. Any thoughts on this?

**Comment by alayek** [comment]
Yes, the second solution alters the original array, while your solution does not. Adhering to the the principles of pure functions, this is a much better solution. Because it doesn't alter anything.

I will remove the second one and include yours, once you are done refining.

**Comment by Rafase282** [comment]
@alayek currently the only idea that comes to mind is to inline the sorting part instead of making it a function, what do you think of it? Worth it or should I leave it as is?

**Comment by alayek** [comment]
@Rafase282 sure, if you inline `return arr.sort((curr, next) => curr > next);`, it doesn't hurt readability.

**Pull request closed without merging**
