### PR TITLE
Arrange operations alphabetically in Swashbuckle Swagger.

### PR DESCRIPTION
**Pull request by pallu**

### CODE REVIEW

**Comment by Rafase282** [comment]
Please rename the filename to follow the guidelines.

**Comment by Rafase282** [comment]
Given the content I'll have to wait on someone with experience on the language to review the content itself.

**Comment by pallu** [comment]
No worries, this was part of [https://github.com/domaindrivendev/Swashbuckle/issues/11#issuecomment-178582333](https://github.com/domaindrivendev/Swashbuckle/issues/11#issuecomment-178582333) where I had commented.

**Comment by Rafase282** [comment]
@pallu please squash and I'll merge.

**Comment by pallu** [comment]
Hi Rafase282. I've never done a squash before and I followed the guidelines on github. I hope I've done it correctly, if not please let me know!
Thanks.

**Comment by Rafase282** [comment]
@pallu you havent done it. Come to the gitter chat?

**Pull request closed without merging**
