### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by xRahul**
**Description**
Removed max-width:960px from .wiki-container

**File**
https://github.com/freecodecamp/wiki/blob/gh-pages/styles.css

**_URL to the panel_**
https://www.freecodecamp.com/wiki/en/

**Before removing the CSS**
screenshot from 2016-04-19 10 56 31

**After Removing the CSS**
screenshot from 2016-04-19 10 57 07

### CODE REVIEW

**Comment by xRahul** [comment]
Related issue:
https://github.com/FreeCodeCamp/wiki/issues/753

**Comment by alayek** [comment]
@xRahul thanks for this PR. But, even though it's a small change in CSS; it's still a site wide change that could affect user experience of a thousands of users.

Please don't mind, I have to block the PR for now. It requires a discussion and quorum between core team members. We will get back to this as soon as possible.

In the meantime, you can chat with us in the [Wiki room](https://gitter.im/FreeCodeCamp/Wiki)

**Comment by xRahul** [comment]
@alayek sure! I get that the change is not conventional and being a change in the core css of the wiki site, it will require some discussion and testing beforehand.

**Comment by abhisekp** [comment]
@xRahul you need not close this though. Let it keep open for review and then if approved, this can be merged.

**Comment by xRahul** [comment]
alright! The change is small, so we can make them after discussion.

**Comment by alayek** [comment]
Nonetheless, the PR should remain open. The `blocked` label makes sure no mod would merge it unless the original label-er removes it.

**Comment by raisedadead** [comment]
@hallaathrad I know you are super busy, but @xRahul has done some good work over here, would you please take a look.

Warning:
This may need to be taken up to the wiki-generator repo when that goes into works.

**Comment by Rafase282** [comment]
Have you tested the responsiveness?

**Comment by hallaathrad** [comment]
Hey all! Thanks go to @xRahul for his contribution!
I'm ok with the change, except it doesn't really fix the underlying issue (what if the screen is actually not broader than 1024px? the images are not adjusting to the screen size so they'd still be hidden for smaller resolutions... for instance). Besides, there's a design principle for lines of text not being longer than 13 words' length, or paragraphs start looking wonky and legibility decreases.

Furthermore, and this is on the procedural side of things. This PR should not be against gh-pages for this one gets overwritten by the generator... @xRahul chat me up on gitter and we can get this thing worked out properly, I'll help if you want me to ;)

It was in my ToDos anyway. What say you?

**Comment by xRahul** [comment]
@hallaathrad Thanks man for making it clear. 
Wiki-generator seems awesome, I'll check it out for any future changes.

**Pull request closed without merging**
