### PR TITLE
Created Article Checkpoint-Profile-Lookup

### PR DESCRIPTION
**Pull request by osterbergmarcus**
Recommit file

### CODE REVIEW

**Comment by osterbergmarcus** [comment]
Not sure how to merge all my commits into a single commit?

**Comment by Rafase282** [comment]
Are you making a branch from the current master? It seems like you are not, also you added the same commits, like the typo and so on. The conflicts are still there. Please redo from a fresh fork of the repo and using a branch with a descriptive name. If for whatever reason you could not make a single commit (make all needed changes all together before pushing it, one save) then here is how to squash them. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one

**Comment by osterbergmarcus** [comment]
@Rafase282 Alright I will try again.. Thanks!
Do you experience any conflicts with the code?

**Comment by Rafase282** [comment]
Github checks and wont allow us to merge until the conflicts it finds are resolved.

**Comment by osterbergmarcus** [comment]
Ah ok. I see..

**Pull request closed without merging**
