### PR TITLE
Splits campsites by countries and then sorts them

### PR DESCRIPTION
**Pull request by bugron**
Closes FreeCodeCamp/FreeCodeCamp#4282.

### CODE REVIEW

**Comment by SaintPeter** [comment]
Would there also be interest in further sub-dividing these by state/province/political subdivision?  At least we could set a standard with the US states.

**Comment by bugron** [comment]
I'm currently finishing the rest of cities and after merging you can do that if you want.

**Comment by SaintPeter** [comment]
@bugron Will do, thanks!

**Comment by bugron** [comment]
OK, ready for the QA.

**Comment by SaintPeter** [comment]
FAN-tastic!

**Pull request merged**
