### PR TITLE
Revert medium-example-wiki-article.md

### PR DESCRIPTION
**Pull request by theflametrooper**

### CODE REVIEW

**Comment by alayek** [comment]
This is to revert earlier [commit](https://github.com/FreeCodeCamp/wiki/commit/f4d5a30d58270794dd2d03788de720be5419e7fe).

# LGTM :+1:

**Comment by Rafase282** [comment]
When was this removed?

**Comment by theflametrooper** [comment]
@Rafase282 Via an accidental direct commit

**Comment by Rafase282** [comment]
Okay, did you use the revert button or just created the article again?

Also what's the point of this file in the first place? Seems to just be placeholder.

**Comment by theflametrooper** [comment]
@Rafase282 I just created it again. But I also think it could be deleted. It was just to resolve the problem where I accidently directly committed to the main repo instead of my fork.

**Comment by abhisekp** [comment]
Let the file remain deleted. It was a placeholder anyway.

**Pull request closed without merging**
