### PR TITLE
Update Git Resources list

### PR DESCRIPTION
**Pull request by raisedadead**
Updating Git Resources with list of Git Articles.

### CODE REVIEW

**Comment by Rafase282** [comment]
Fancy table.

**Comment by raisedadead** [comment]
Umm this confuses me! Are you approving it or rejecting it! :fearful:

**Comment by raisedadead** [comment]
@Rafase282 On a side note however I guess we could come up with a way to hot wire the CamperBot to point to the list? Not sure what should be the format. Do you have any pointers on that? or maybe @ltegman is the expert on everything bot?

**Comment by Rafase282** [comment]
@raisedadead the table is nice but a simple ordered list would achive the same result and make it easier to maintain. However if people want to use the table I wont oppose to it. I would personally prefer:

1. A nice
2. Ordered
3. List
4. Like this.

**Comment by Rafase282** [comment]
@raisedadead currently this is what is shown when you do a `wiki git` [url](https://github.com/freecodecamp/freecodecamp/wiki/challenge-save-your-code-revisions-forever-with-git)

**Comment by raisedadead** [comment]
@Rafase282 I recommend we move to a simpler un-ordered list that's sorted alphabetically, it would be much simpler to add entries that way without making too many changes to the entire list.

And thanks for the guidance on the bot, I'll check and update once I figure out.

**Pull request merged**
