### PR TITLE
Update algorithm truncate

### PR DESCRIPTION
**Pull request by bmorelli25**
Added in an advanced one-line solution that uses nested ternary operators. The solution also utilizes the slice() method - which is what the student is "supposed" to use to solve this Algorithm challenge. The current solution uses the substr() method, so I added that into the hint section as well.

### CODE REVIEW

**Comment by Rafase282** [comment]
As I discussed in the public chat yesterday, I don't like the idea of nesting ternary operators because it can be a pain to read the code, being a one line does not make it always better.

```js
function truncateString(str, num) {
  // Clear out that junk in your trunk

  if (str.length <= num) {
    return str;
  } else {
    return str.slice(0, num > 3 ? num - 3 : num) + '...';
  }
}

truncateString("A-tisket a-tasket A green and yellow basket", 11);
```

This is the solution I decided on sticking.

**Comment by bmorelli25** [comment]
Oh it certainly is a pain to read - just figured it would be good for students to get experience with learning how to read them so they can figure out what in the heck is going on if they ever see it again.

But, that's fair. I'll swap the code with your recommendation above so we get the best of both worlds.

**Comment by Rafase282** [comment]
@bmorelli25 would you mind trying to see if we [our slice article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/JS-Array-Prototype-Slice) instead of the link you provided?

Also I will need you to update the whole article as stated on #1094 and leave only our names on the thank section. The script would be on the advance category.

Please add this as the basic one:

```js

function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num && num > 3) {
    return str.slice(0, (num - 3)) + '...';
  } else if (str.length > num && num <= 3) {
    return str.slice(0, num) + '...';
  } else {
    return str;
  }

}

truncateString("A-tisket a-tasket A green and yellow basket", 11);
```

**Comment by bmorelli25** [comment]
Will do

**Comment by bmorelli25** [comment]
Committed and ready for feedback!

**Comment by Rafase282** [comment]
Thanks, great work.

**Pull request merged**
