### PR TITLE
Campsites in JSON

### PR DESCRIPTION
**Pull request by samosale**
Campsites list in JSON with coordinates.

Closes #536

### CODE REVIEW

**Comment by samosale** [comment]
#536

**Comment by abhisekp** [comment]
I think coordinates are messed. I could only verify for Coordinates of Bhubaneswar which is "20.2700° N, 85.8400° E" but in the JSON, this coordinate is assigned to the next city after Bhubaneswar i.e. "Bikaner".

**Comment by abhisekp** [comment]
Even the coordinates of "Bikaner" originally "28.0167° N, 73.3119° E" is messed up in the JSON file.

**Comment by samosale** [comment]
will fix that

**Comment by alayek** [comment]
@samosale kindly tell us what's the status on this.

**Comment by abhisekp** [comment]
@samosale Why is everything in one line?

**Comment by samosale** [comment]
@abhisekp that's how node.js and Cloud9 have done it. I think I use appendFile() in Node. You can see it raw.

**Comment by samosale** [comment]
@alayek I think I will have full list by the end of a day.

**Comment by abhisekp** [comment]
@samosale it would be better and easier for readability to use a JSON formatter and beautify it.

E.g. https://jsonformatter.curiousconcept.com/

**Comment by Rafase282** [comment]
What is the status of this? Is the only thing needed is beautify the file?

**Comment by alayek** [comment]
@samosale please take a look at this when you get time.

**Comment by theflametrooper** [comment]
@samosale Here is a link to the JSON beautified: https://ghostbin.com/paste/fttsk

**Comment by theflametrooper** [comment]
@samosale Are you available to update this PR with the suggested changes?

**Comment by samosale** [comment]
@theflametrooper yes, I am now.

**Comment by samosale** [comment]
How to delete or merge previous commits? The right one is final-version-end 
https://github.com/FreeCodeCamp/wiki/pull/628/commits/6fd30044596e738ba6cb4e0ff85ee50015144bc1

**Comment by Rafase282** [comment]
@samosale do got rebase -I HEAD~# where # is the total number of comits, then leave the top one as is and all others change to s

Then force push

**Comment by samosale** [comment]
@Rafase282 But I don't want the content of previous commits to be included in the final commit. Should I  delete previous commits?

**Comment by abhisekp** [comment]
@samosale 
<br>
<br>

> ----
<p align="center">Need Help? Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>or Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Comment by Rafase282** [comment]
@samosale if you squash then it will put all into one with the last commit being the last change applied. Also if you remove commits when squashing they will be removed.

**Comment by samosale** [comment]
@Rafase282 I  get an error `It seems that there is already a rebase-merge directory, ....`. I tried with git rebase --continue and get error also- `could not apply 5eba90a... Campsites in JSON`. Should I git rebase --skip or git rebase --abort or 	rm -fr "/home/darko/wiki/.git/rebase-merge"
?

**Comment by Rafase282** [comment]
`git rebase --abort` and try again

**Comment by samosale** [comment]
@Rafase282 Ok, I done that but I can't see my latest three commits just the older ones...

**Comment by Rafase282** [comment]
You mean this one 6fd30044596e738ba6cb4e0ff85ee50015144bc1 ?

**Comment by samosale** [comment]
Yes, I can't see that nor previous two.

**Comment by Rafase282** [comment]
It is here, I guess you squashed some, you would have to force push, but I can just squash from here and then you can check the merged file, it should be the last version you had.

**Comment by samosale** [comment]
Ok, try it.

**Comment by Rafase282** [comment]
@samosale it is done, here it will have all the commits but in the repo which I just updated it will be as one commit. Thank you for your work.

**Comment by samosale** [comment]
@Rafase282 It's been a pleasure. Tnx @all  sugestions.

**Pull request merged**
