### PR TITLE
Article Update : Bubble sort

### PR DESCRIPTION
**Pull request by jainaman224**
#1048

### CODE REVIEW

**Comment by Rafase282** [comment]
```diff
-Algorithms-BubbleSort.md
+Algorithms-Bubble-Sort.md
```

```diff
-# BubbleSort
+# Algorithm Bubble Sort
```

**Comment by jainaman224** [comment]
I think this is already in your repository, then it would create new file.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles:

**Comment by alayek** [comment]
# LGTM :+1:  

Let's :shipit: :package:

**Pull request merged**
