### PR TITLE
Added Raleway Font

### PR DESCRIPTION
**Pull request by theflametrooper**
#### The anchor tags may need updated. What do you think @raisedadead ?
---------------
_Screenshot of new design:_

### CODE REVIEW

**Comment by raisedadead** [comment]
LGTM. But as always be aware that the gh-pages will get overwritten by wiki-generator. So it will have to be taken up then once again.

**Comment by Rafase282** [comment]
Why not directly modify the files so the generator will keep the style changes?

**Comment by theflametrooper** [comment]
@Rafase282 Where is that file located? I was unaware of it's existance...

**Comment by theflametrooper** [comment]
Closing this pr and will open a new one here: https://github.com/FreeCodeCamp/wiki-generator

**Pull request closed without merging**
