### PR TITLE
Update bonfire-find-the-longest-word-in-a-string.md

### PR DESCRIPTION
**Pull request by shadowfool**
Added a recursive solution to this problem.

### CODE REVIEW

**Comment by Rafase282** [comment]
@shadowfool you should just add your name to the credit section instead of putting your name on the "title"

**Comment by shadowfool** [comment]
Updated to reflect @Rafase282 suggestion

**Comment by shadowfool** [comment]
Fixed

**Comment by SaintPeter** [comment]
Merged, Thanks!

**Comment by BerkeleyTrue** [comment]
@FreeCodeCamp/teamwiki Don't forget to push to the wiki.

**Pull request merged**
