### PR TITLE
update easy to first timers only

### LINKED ISSUE #866: Small update on article on labels in main repo
The `easy` label should be changed to `first timers only` as we recently changed it.

https://github.com/FreeCodeCamp/wiki/blob/master/Select-Issues-for-Contributing-Using-Labels.md

image

### PR DESCRIPTION
**Pull request by lesliekimm**
Hello! quick simple fix for MD file 👍 

- Edited Filename: Select-Issues-for-Contributing-Using-Labels.md

Closes #866

### CODE REVIEW

**Comment by Rafase282** [comment]
Hello, it might be covered here https://github.com/FreeCodeCamp/wiki/pull/886

**Comment by lesliekimm** [comment]
@Rafase282 for future reference, do you know how I can tell if someone has already created a PR for an issue?

**Comment by iheartkode** [comment]
@lesliekimm  Best way is to just search the PR's

**Comment by Rafase282** [comment]
You can check the issue if one is open, otherwise the chat is the best place next to checking pull request.

[Chat](https://gitter.im/FreeCodeCamp/Wiki?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
[PR](https://github.com/FreeCodeCamp/wiki/pulls)

**Comment by iheartkode** [comment]
Look at the filter input and just type something in there :)

**Comment by theflametrooper** [comment]
Closing as duplicate of #886.

**Pull request closed without merging**
