### PR TITLE
Fix: Python Function Decorators

### PR DESCRIPTION
**Pull request by ds-249**

### CODE REVIEW

**Comment by atjonathan** [comment]
@alayek, please take a look :stuck_out_tongue_winking_eye:

**Comment by alayek** [comment]
Looks great, but I kinda feel like you could have added different example application of decorators. Like, exception handling, for example.

Anyway, I have no issue merging this!

# LGTM :+1:  

Let's :shipit: :package:

**Comment by atjonathan** [comment]
@ds-249, do you wanna make the changes @alayek suggested? If not, I will press that big merge button :stuck_out_tongue_winking_eye:

**Comment by atjonathan** [comment]
@ds-249 Thanks for all the work you've done on wiki articles so far! Keep them coming :tada:

**Comment by ds-249** [comment]
Sure thing. :)

**Pull request merged**
