### PR TITLE
New Solution for Bonfire:Search and Replace using regular expressions

### PR DESCRIPTION
**Pull request by coded9**
Using Regular Expressions

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Please make the title descriptive and specific.

**Comment by coded9** [comment]
Hi Berkeley, does it need more explanation ?

**Comment by BerkeleyTrue** [comment]
Yes, that is why I asked.

**Comment by BerkeleyTrue** [comment]
To be clear I'm referring to the title of this PR.

**Comment by coded9** [comment]
I mean like this  "New Solution for Bonfire:Search and Replace using regular expressions" ??

**Comment by BerkeleyTrue** [comment]
Sure

**Comment by coded9** [comment]
I'm done with my part.. Now,it's your time to review

**Comment by SaintPeter** [comment]
Please squash your commits.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase

**Pull request closed without merging**
