### PR TITLE
Added Solution #2 to Bonfire Seek and Destroy page

### PR DESCRIPTION
**Pull request by livike**
- Added Solution 2, 
- enlarged hints for solution 2

### CODE REVIEW

**Comment by Rafase282** [comment]
I'm not so sure about the solution. If anything the only thing I can see from there teaching something new would be the fact that you can use a function that was already declared with filter. That's not new to me and it was common sense when I learned about filter but I'm not sure if others know this too.

I would like some feedback from @FreeCodeCamp/teamwiki @FreeCodeCamp/wiki-editor 

I would like to limit the code solutions to things that improve on the previous teach something more advance and have a base code with the bare minimum based on the links mentioned on the bonfires and such.

**Comment by SaintPeter** [comment]
This is really not a very good solution.  I think it's harder to read and understand that the prior solution and while it is vaguely different, it's also less efficient.

**Comment by livike** [comment]
Thanks for the feedbacks.
@Rafase282 : The callback function was created exclusively for the filter. I learned about filter() from the link mentioned on the bonfires and the first example was the callback function defined separately.
However I tried to put the function directly in filter, but the FCC code editor put the warning to not make functions within a loop. For this is the callback function separately.

@SaintPeter : personally, at first I find a little hard to understand the solution in the wiki, for this reason wanted to create my own, maybe less elegant and efficient.
I like the fact that in many wiki hint pages you can find many different ways to solve the problem. Looked like a good possibility to contribute and submit one different.
However if you find it so bad, we can not include it.

**Comment by Rafase282** [comment]
@livike the thing is with filter, you don't need a loop. It has one built inside which is why you don't see on one the example I provided. They are redundant and using them defeats the purpose of using filter at all, at least for this problem.

**Pull request closed without merging**
