### PR TITLE
Updated map links

### PR DESCRIPTION
**Pull request by leftynaut**
All are working but Record Collection. Maybe it has yet to be pushed
live?

### CODE REVIEW

**Comment by leftynaut** [comment]
Not sure how the remote-tracking branch got on here. Ignore that commit if possible.

**Comment by hallaathrad** [comment]
reset head?

**Comment by SaintPeter** [comment]
It is not possible to "ignore" commits.  The way that happened is that you did a `git pull` on your local fork and it added a commit.

Here is a detailed guide:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Contribute-To-The-Wiki

Regardless, I'll accept it.  It's just the Wiki.  ;)

**Comment by hallaathrad** [comment]
Hahaha "just the wiki"... Jee, thanks @SaintPeter! But you're right, I'm sure nobody will even notice or mind.

**Pull request merged**
