### PR TITLE
Update Clementine installaton instructions

### LINKED ISSUE #568: Update How to get the MEAN stack running locally on OSX
Refering a [comment on chat](https://gitter.im/FreeCodeCamp/HelpContributors?at=56e409177fefcd2a398c9f48)

The article [How to get the MEAN stack running locally on OSX](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-the-MEAN-stack-running-locally-on-OSX) needs to be updated.

### PR DESCRIPTION
**Pull request by awesomeaniruddh**
Updated the installation instructions article to include a link to the official Clementine installation instructions.

Closes #568

### CODE REVIEW

**Comment by Rafase282** [comment]
Why did you delete the mean stack guide?

**Comment by awesomeaniruddh** [comment]
Because it was for angular-fullstack which we don’t endorse anymore? Plus we intend to teach React (which I believe will be integrated with Clementine) instead of Angular, so…?

Aniruddh Agarwal

Sent from
https://polymail.io/

On Wed, 16 Mar 2016 at 9:16 PM "Rafael J. Rodriguez"

<
mailto:
> wrote:

Why did you delete the mean stack guide?

**Comment by abhisekp** [comment]
@awesomeaniruddh even FCC is not teaching Angular, we don't have to remove the guide. FCC is accepting all types of technical articles. 

Things to todo
- [ ] Restore the MEAN stack guide.

**Comment by awesomeaniruddh** [comment]
Okay, but I’ll have to clean the article up. It referred to some content from FCC that no longer exists and is OS X only.

I’ll remove the content that exists on the Clementine page and remove the outdated references.

Aniruddh Agarwal

Sent from
https://polymail.io/

On Wed, 16 Mar 2016 at 9:24 PM Abhisek Pattnaik

<
mailto:Abhisek Pattnaik <notifications@github.com>
> wrote:

https://github.com/awesomeaniruddh
even FCC is not teaching Angular, we don't have to remove the guide. FCC is accepting all types of technical articles.

Things to todo

Restore the MEAN stack guide.

**Comment by abhisekp** [comment]
@awesomeaniruddh About cleaning up the MEAN stack, that can be done in another PR.

**Comment by awesomeaniruddh** [comment]
Done.

**Comment by abhisekp** [comment]
# :+1: LGTM

**Pull request merged**
