### PR TITLE
Updated recently merged article

### PR DESCRIPTION
**Pull request by Rafase282**
Now it has links without the repeated name, I think it looks better that way, also fixed some minor indentation issues. There  are more links from here that could be added so it would be nice to know about the criteria @ianseabrook used on PR #396

### CODE REVIEW

**Comment by Rafase282** [comment]
@ianseabrook ^

**Comment by ianseabrook** [comment]
Unclear how I fit into this. Did you mean to tag @ibrahimelbanna?

**Comment by Rafase282** [comment]
Yes sorry, I'm not sure how I got the named mixed up.

**Comment by Rafase282** [comment]
@ibrahimelbanna I want to know if you filtered the links by relevance and working links or if you just choose the ones you liked so I know whether to add more links or not.

**Comment by ianseabrook** [comment]
No worries. Guess I'm alphabetically first on autofill ;) Oh well, back plotting world domination from my cloudbase! alt text

**Comment by ibrahimelbanna** [comment]
I choose the ones i liked and i  will add the rest , I just want to test if i will get my contribution accepted or not

**Comment by Rafase282** [comment]
Alright then, just try to look at the changes I made so you keep the same format.

**Pull request merged**
