### PR TITLE
Add cities, May 18 2016

### LINKED ISSUE #984: City listed in wrong state : 'Noida' is in 'Uttar Pradesh'
From FreeCodeCamp/FreeCodeCamp#8714

> #### Challenge Name
> City listed in wrong state
> https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/LocalGroups-List

> #### Issue Description
> Indian city 'Noida' is listed in 'Haryana' State, whereas 'Noida' is in 'Uttar Pradesh'

 
> #### Screenshot

image

### PR DESCRIPTION
**Pull request by hallaathrad**
also, closes #984

### CODE REVIEW

**Comment by theflametrooper** [comment]
@hallaathrad In future, leave issues with the `first-timers-only` label for users who haven't submitted a PR before. I'll merge this anyway as there is no point in waiting for another PR. Thanks!

**Comment by hallaathrad** [comment]
Will do. Thanks for filling me in on that part of your workflow. I've merely seen myself tagged in that issue, figured someone wanted me to deal with it.

**Comment by theflametrooper** [comment]
@hallaathrad Oh I see that, no worries :stuck_out_tongue_winking_eye:

**Comment by Rafase282** [comment]
I tagged him because it was related to Local groups, so whether he did it or let someone else he should be in the loop, and mostly because I don't like leaving know bugs open indefinitely until someone comes along to make their first contribution.

That label should not be used for bugs but for new content in my opinion, unles you already have an candidate ready to fix it. @theflametrooper @raisedadead

**Comment by theflametrooper** [comment]
@Rafase282 Sounds like a good idea to me ;)

**Pull request merged**
