### PR TITLE
Fix Code Formatting markdown

### PR DESCRIPTION
**Pull request by abhisekp**

### CODE REVIEW

**Comment by atjonathan** [comment]
@abhisekp, please make your changes on the [forum](http://forum.freecodecamp.com) :smiley:

**Comment by abhisekp** [comment]
@atjonathan please merge this for the love :heart: of camperbot :smile: 

This change is required for it to be reflected in the chat room.
I guess, camperbot has not been updated to fetch from forum instead of the wiki. :wink:

**Comment by atjonathan** [comment]
@abhisekp lol
@rafase282 leaving this to you :joy:

**Comment by Rafase282** [comment]
Don't tell nobody we accepted a PR... lol

**Pull request merged**
