### PR TITLE
Update city-based campsites link on chat room page

### PR DESCRIPTION
**Pull request by lilyheart**

### CODE REVIEW

**Comment by Rafase282** [comment]
Hello, would you mind changing the hard link to a relative one for the code of conduct?

**Comment by Rafase282** [comment]
Something went wrong. There are some conflicts. Are you making these changes fromt he browser or locally?

**Comment by lilyheart** [comment]
From the browser.

**Comment by Rafase282** [comment]
I think it would be best to submit a new PR with just the changes.

**Comment by lilyheart** [comment]
I was literally just typing that.  My rebase seems to have picked up another file.

**Pull request closed without merging**
