### PR TITLE
Create Use codes on local machine for front-end development.md

### PR DESCRIPTION
**Pull request by ishitach**
Use this guide for running codes made for front end development on your local machines.

### CODE REVIEW

**Comment by raisedadead** [comment]
@ishitach Thanks for the PR. 

We sincerely appreciate the effort. But the nature of this article sounds more like a blog. But IMHO, the FreeCodeCamp/Wiki is more oriented in definitive guide towards common and/or specific targeted problems.

This wiki entry should there for be enhanced to feel like a guide to be accepted. Feel free to discuss this in our [Help Chat room](https://gitter.im/FreeCodeCamp/Wiki).

I am keeping this open for opinion from @Rafase282 

P.S: There are a few review comments too, about the format.

**Comment by Rafase282** [comment]
@raisedadead I totally agree with you. I would suggest a rewrite with a shorter yet self explanatory title, and better formatting with enhanced content.

**Comment by ishitach** [comment]
@raisedadead  @Rafase282 Sorry, this was my first commit. Will improve it and will let you know. Thanks for your feedback.

**Comment by raisedadead** [comment]
@ishitach Definitely! Looking forward for the contribution, thanks.

**Comment by Rafase282** [comment]
@ishitach Feel free to create a new Pull Request when you are ready. There has been many changes since you created this one and I strongly suggest you create yours based on a fresh master. With that said, I'm closing this pull request, thanks.

**Pull request closed without merging**
