### PR TITLE
Update Algorithm Chunky Monkey

### LINKED ISSUE #1205: Chunky Monkey needs better solutions
Referring https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9500
> The basic solution is very convoluted and intermediate isn't much better. Advanced is OK.
>
> Challenge also might benefit from mentioning the <code>splice</code> method since that is a much simpler approach than <code>slice</code>.
>
> Propose eliminating that ugly basic solution, demoting intermediate to basic, and advanced to intermediate. Also recommend adding <code>splice</code> to list of suggested methods.

### PR DESCRIPTION
**Pull request by dakshshah96**
Closes #1205.
- Add new **Basic** solution which uses the `splice()` method.
- Add simplified **Intermediate** solution which uses the `slice()` method.

@raisedadead: What do you think of this?

@Rafase282: Regarding the names in **Credits**, are there any I should remove?

### CODE REVIEW

**Comment by atjonathan** [comment]
### **LGTM :+1:**

**Comment by Rafase282** [comment]
Personally I think there is no much difference between the old intermediate and the new basic.

From the previous ones, the basic was the only that was different and used basic functions and iterators, the others use slice and splice that while are not the same does similar thigns and overall the code was similar.

I vote for keeping the old basic.

@dakshshah96 as for the names, these challenges have already been moved to the forum where the whole credit section has been removed as the new standard.

**Comment by atjonathan** [comment]
I agree with @Rafase282 with further scanning.

**Comment by alayek** [comment]
In general, I would recommend against `splice()` method. It alters or mutates the original array. Does not adhere to good practices of functional programming, namely, writing pure functions that always produce same outputs for same inputs.

Always use `slice()` over `splice()` when you can. Same goes for `concat()` vs. `push()`.

**Comment by Rafase282** [comment]
That's a good point, I didn't check that. In some challenges we are not supposed to modify the original array.

**Pull request closed without merging**
