### PR TITLE
#344 campsites to json - lat/lon blank

### PR DESCRIPTION
**Pull request by LibertysYarn**

### CODE REVIEW

**Comment by Rafase282** [comment]
@hallaathrad can you check this out?

**Comment by hallaathrad** [comment]
Looks legit to me, though I wonder about sustainability, considering we add so many cities every single day. @Rafase282 

@LibertysYarn how does this json handle the `"lat": , "lon"; `? do these come off as undefined? or blanks? or does it simply turn into an error?

**Comment by LibertysYarn** [comment]
I'm pondering on it. Also trying to estimate length of time for me to fill
all of those in. I can change them all to null for now.

**Comment by Rafase282** [comment]
What's the status on this? Ready to Squash and merge or there is no resolution yet?

**Pull request merged**
