### PR TITLE
new waypoints between checkpoints 77 and 90

### PR DESCRIPTION
**Pull request by CaroleAnneHannon**

### CODE REVIEW

**Comment by Rafase282** [comment]
Please use '''js or '''JavaScript on the code quotes

**Comment by CaroleAnneHannon** [comment]
I didn't do them any different than how you did this one:
https://github.com/FreeCodeCamp/wiki/blob/9672fe5edaeb2d47ab2fde82557ed893a31271fc/Waypoint-Finding-a-Remainder-in-Javascript.md

I don't see '''js or '''JavaScript on yours

You used ``` and so did I.

**Comment by Rafase282** [comment]
That's because it was more of a math example than code itself. But what it does is is syntax highlight.

**Comment by CaroleAnneHannon** [comment]
done

**Pull request merged**
