### PR TITLE
Article: Agile Manifesto

### PR DESCRIPTION
**Pull request by SeanFCC**
Creation of article title The Agile Manifesto.

See https://github.com/FreeCodeCamp/wiki/issues/667

### CODE REVIEW

**Comment by alayek** [comment]
The file extension should be `.md`, not `.mdm`.

**Comment by SeanFCC** [comment]
@alayek DOH! Thank you Arijit.

**Comment by SeanFCC** [comment]
Added link to original site.

**Comment by Rafase282** [comment]
@SeanFCC please move the file from the directory so we only have the file itself and it will be ready to be merged.

**Pull request closed without merging**
