### PR TITLE
For loop explained changes

### PR DESCRIPTION
**Pull request by gurulearningxyz**
Adding explanation and code for for loops.

### CODE REVIEW

**Comment by SaintPeter** [comment]
This is some pretty good description, but the "Statement 1/2/3" actually have names:
`for ([initialization]; [condition]; [final-expression])`

You should harmonize your changes with what is stated here:
http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops

**Comment by gurulearningxyz** [comment]
Updated pull request based on the feedback received. Thanks!

**Comment by SaintPeter** [comment]
Two things:
1) Can you format all the code as code blocks?
2) Can you squash your commits, or resubmit as a single commit?

**Comment by gurulearningxyz** [comment]
Updated pull request with latest feedback.

**Comment by bugron** [comment]
@gurulearningxyz, please, read [this Wiki article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase) and `squash` your commits into one single commit.

**Comment by Rafase282** [comment]
I don't think he is going to do it, at least not any time soon @bugron

**Comment by bugron** [comment]
@Rafase282 then we can merge this if all looks good.

**Pull request merged**
