### PR TITLE
Fix algorithm caesars cipher

### PR DESCRIPTION
**Pull request by alayek**
This is a fix to the issues raised in https://github.com/FreeCodeCamp/wiki/pull/677

I have moved and updated the solutions as @abhisekp has mention [here](https://github.com/FreeCodeCamp/wiki/pull/677#issuecomment-205645189).

I have also added functional solution by @abhisekp in the advanced section.

I have not included any constants to replace the magic numbers, because that would be overkill!

### CODE REVIEW

**Comment by alayek** [comment]
@SaintPeter @Rafase282 please take a look.

**Comment by Rafase282** [comment]
Second solution does not work. See the wiki chat.

Imgur

For the advanced one:

I think this is a bug on FCC but still pointing that out.
Imgur

**Comment by abhisekp** [comment]
@Rafase282 that warning is because FCC editor uses JSHint as the linter and probably, has not set `esversion: 6` in its options somewhere (*i'm not sure about the options thing though*).

I don't think it's required to add `esversion: 6` as it's unrelated to the code and is an optional thing which is related to the editor the code is executed in.

**Comment by Rafase282** [comment]
@abhisekp yeah i was told about that which is why I pointed to the chat, I didn't remove it so in the future we have a reference if we use the code and campers get concerned about.

The bug part is because the intermediate code is not working.

**Comment by SaintPeter** [comment]
@abhisekp Would you be willing to write up a more detailed explanation for your super-tight functional solution?

**Comment by Rafase282** [comment]
@alayek what's the status of this PR?

**Comment by abhisekp** [comment]
@Rafase282 I need some time to think about the logic I used and try to explain it in most succinct way.

**Comment by abhisekp** [comment]
<h1 align="center"><a href="https://github.com/FreeCodeCamp/wiki/pull/689#issuecomment-207077267">TODO</a></h1>

Write an easy to understand explanation of :rotating_light: **Advanced Solution**.

**Pull request merged**
