### PR TITLE
Addition to Algorithm-Search-and-Replace.md

### PR DESCRIPTION
**Pull request by Scoodood**
Algorithm-Search-and-Replace.md

Added code solution 4, the code is shorter and cleaner and yet still get the
job done efficiently.

### CODE REVIEW

**Comment by alayek** [comment]
@Scoodood thanks for this PR. We are grateful you have taken an interest in improving our Wiki.

Coming to your PR, it surely is a bit different from what we already have in [code solution 2](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Search-and-Replace#code-solution-2).

But at the same time, it's not too different. The code solution 2 works almost the same way as your solution does.

About your comments on shorter code, we accept shorter code only if it doesn't hurt readability. It's not shorter than code solution 2.

As for efficiency, unless you have benchmarks to back that up; we cannot accept the measure.

---

I am **not** willing to merge this. But I would let other mods have a go at it.

@abhisekp @SaintPeter @Rafase282 @raisedadead what do you guys think?

**Comment by Rafase282** [comment]
Also note, we are not accepting PR for algorithm solutions with new solutions unless they also include the new [template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution)

**Comment by abhisekp** [comment]
@Scoodood Are you willing to contribute in Wiki in a very different and smart way? :wink: 
Help us in converting our algorithms solutions using the latest and greatest 
 [Wiki Template Challenge Solution](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution)

**Comment by Scoodood** [comment]
Hi all, this is my first time contributing to the FCC so please forgive me if I missed out a few steps here and there.

Hi Rafase282, please help me understand more about the template requirement you mentioned above. I thought the original Algorithm-Search-and-Replace.md is already using the template format, all I did was just appending new solution at the end of it and do a PR. So the revised .MD is still with the template format. May I know what do you really mean by "unless they also include the new template". Please enlighten.

Thanks :)

**Comment by Rafase282** [comment]
@Scoodood sure, [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution) template is different, it might look similar but one of the main thing is no more than 3 solutions.

Could you please come over to the [chat](https://gitter.im/FreeCodeCamp/Wiki) so i can tell you in more details?

**Comment by alayek** [comment]
@Scoodood we are really glad to have someone like you interested in contributing. You can reach out to us in [Wiki room](https://gitter.im/FreeCodeCamp/Wiki)

**Pull request closed without merging**
