### PR TITLE
Comparison Operators

### LINKED ISSUE #362: rewrite and simplify explanation of Comparison Operators
Original issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3466

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

### PR DESCRIPTION
**Pull request by rishipuri**
closes #362 

Lemme know if any changes needed.

### CODE REVIEW

**Comment by Rafase282** [comment]
I would go about the heading in order.

1. # for the title
2. ## for subtitles, this should be the main level for topics related to 1.
3. ### For sub topics inside 2.
4. #### if needed for things inside 3. 

Ans so on.

**Comment by rishipuri** [comment]
@Rafase282 Updated.

I have kept the syntax and example headers as same for the text effect.

**Comment by Rafase282** [comment]
Alright, I see that. Looks good. Just please squash.

**Comment by rishipuri** [comment]
@Rafase282 Done. :)

**Comment by Rafase282** [comment]
Awesome, merged.

**Pull request merged**
