### PR TITLE
Fix broken link in How to Create a Pull Request article

### PR DESCRIPTION
**Pull request by tonymorristm**

### CODE REVIEW

**Comment by Rafase282** [comment]
@tonymorristm the link works fine, see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp and try it out.

**Comment by tonymorristm** [comment]
@Rafase282 Sorry, this was my first pull request and I guess I should have should have been more descriptive. If you go to the article via the FCC Wiki, this is the link to the article (https://www.freecodecamp.com/wiki/en/how-to-create-a-pull-request-for-free-code-camp/).
The link in question is titled ( How to Setup and Maintain a Local Instance of Free Code Camp) and I get a 404 error when clicked.

The link you posted above works but it seems to be at a different location.

What am I missing, please?

**Comment by Rafase282** [comment]
The link you just posted works. However, If I'm correct that version of the wiki is not up to date yet. Still a work in progress.

**Comment by alayek** [comment]
@tonymorristm the way our Wiki works is that we merge Wiki articles via PR in this repo. Then there is a script, that takes the content here and merges with Wiki section of main FCC repo.

Now, relative links won't work locally, or even after merging to Wiki repo. But once we merge the Wiki repo to main repo's Wiki section, GitHub picks it up and makes it work.

**Comment by tonymorristm** [comment]
Thanks guys for the info, sorry I'm still a little confused though.:(
The link I posted works but the link inside the article does not work for me. 
It is contained in this sentence: "This is the recommended method. Read about How to Setup and Maintain a Local Instance of Free Code Camp." https://www.freecodecamp.com/wiki/en/how-to-create-a-pull-request-for-free-code-camp/

@alayek Thanks for the explanation. To make sure I understand the process:
-the articles/etc are created and put in this repo
-they are updated/etc via PR's
-a script merges this updated content up to the FCC Wiki page (https://www.freecodecamp.com/wiki/en/)
-not all of the content on this repo is up to date on the FCC Wiki page
I'm a little fuzzy on the relative links info though.

**Comment by alayek** [comment]
@tonymorristm no, I meant Wiki of the main repo: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki

Take the article you have cited, for example. The corresponding article on Wiki of main repo is [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Create-A-Pull-Request-for-Free-Code-Camp)

**Comment by tonymorristm** [comment]
@alayek Ok, so I see if I follow the link to the repo you provided and the article I cited, it does work correctly.

If I am on the FCC Page and select the Wiki page, that is the what is not completely up to date, correct?

**Comment by Rafase282** [comment]
The articles from this repo are pushed to the FreeCodeCamp repository's wiki. There is a script that takes the articles from this repo and push them to a react version of the wiki that is what you see when you click `wiki` on the site.

**Pull request closed without merging**
