### PR TITLE
Update Algorithm-Check-for-Palindromes.md

### PR DESCRIPTION
**Pull request by LGgit**
# FreeCodeCamp - Wiki Pull Request Template
Make sure your contribution addresses the points mentioned below:

**Filenames:**
- Your filename should NOT contain any special characters or spaces.
- Use only `-` to separate words in the filename.
- Filenames should have the `.md` extension.
- Filenames should follow a Camel-Case format such as : `Title-For-The-Article.md`

**Formatting:**

Ensure that you use markdown syntax for articles, we do not accept `HTML` or `CSS` or anything else other than markdown. **Please Checkout these guides for reference:**
- [Master Markdown](https://guides.github.com/features/mastering-markdown/)
- [Working with Advanced Formatting](https://help.github.com/articles/working-with-advanced-formatting/)

**Commits and Squashing:**
- Your Pull Request/Submission should have only one commit.
- For multiple commits follow the [guide to squash them](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one)
- If you are new to contributing then you can [use the browser](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Guide-Online-Contribution), and we will squash multiple commits for you if requested.
- However, for more control over the pull request we recommend that you [use the local method](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Contribute-To-The-Wiki) and request you to squash the commits yourself.

**Signing off:**
- If we merge your pull request, your name will be automatically added to the
- document history on GitHub, and the repo's contributors.
- Please don't add additional bylines when creating or editing an article.

Put `closes #XXXX` in your comment to auto-close the issue (if applicable),  only if your Pull Request is addressing the issue COMPLETELY, else just leave  a comment on the original issue with the Pull Request number.

### CODE REVIEW

**Comment by Rafase282** [comment]
Right now I would hold off on challenges solution until we implemente this [format](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Solution-Template) @abhisekp what do you think?

**Comment by abhisekp** [comment]
@Rafase282 If someone doesn't want to modify the existing challenge format to match the new format and just want to add a new solution, then I don't think that's an issue. The reformatting can be done by us (_Wiki maintainers_). 

----
@LGgit the fourth solution is a partial mix of first and second solutions. 
- Also, you don't need ALL the characters in the regex `/([-_.,*+?^=!:${}()|\[\]\/\\])/`. See how other solutions are implemented using regex. 
- And use proper variable names.

**Comment by Rafase282** [comment]
@abhisekp Alright, just checking because of the way i was thinking about handling the format change. I'll tell you in the chat.

**Comment by LGgit** [comment]
@Rafase282  @abhisekp  I updated the file with the changes.  Although I don't fully understand "use proper variable names"   thanks!

**Comment by abhisekp** [comment]
@LGgit We're accepting only top 3 solutions for each category i.e. Basic, Intermediate and Advanced. Your proposed solution needs improvement regarding elegance. The other existing solutions are more elegant.

You may post your solution in [**`FreeCodeCamp/CodeReview`**](https://gitter.im/FreeCodeCamp/CodeReview) room for feedback.

> Also see :point_right: [**`Challenge Solution Template`**](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Challenge-Solution-Template) for reference.

----
@Rafase282 I think this PR may be closed.

**Comment by LGgit** [comment]
@Rafase282  I understand. thank you

**Pull request closed without merging**
