### PR TITLE
Article: About PHP

### PR DESCRIPTION
**Pull request by tom103**
Created PHP page giving brief purpose of the language along with links to the PHP documentation and release notes. Will update this page as I build out the educational pages starting with the basics. I've thrown in a few of the subjects I'll be covering in the near future so that people can see what is to come and I also don't forget what to work on.

### CODE REVIEW

**Comment by alayek** [comment]
@tom103 I am really sorry man. This [article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Php) already exists.

Modify your PR by removing this file; and adding some of the stuff to "PHP Basics" or some similar file.

**Comment by alayek** [comment]
@Rafase282 @abhisekp @koustuvsinha please take a look. I might have assigned wrong labels,

**Comment by abhisekp** [comment]
@tom103 thank you for the article but as @alayek wrote, there is already an article similar to the one you've written.

You're welcome to improve the existing article and file a pull request. It's a community wiki.

**Comment by tom103** [comment]
No worries. I'll let the original keep rocking. I'd rather just get going with teaching the code. Going to try and figure this github process out, hope I don't become too annoying lol.

**Comment by abhisekp** [comment]
@tom103 If you need any help understanding the github process, you may contact us in our chat.

<br><br>

> ----
<p align="center">Read <a href="https://github.com/FreeCodeCamp/wiki/blob/master/.github/CONTRIBUTING.md"><b>CONTRIBUTING</b></a> Guidelines<br>Chat with us in <kbd><a href="https://gitter.im/FreeCodeCamp/Wiki"> <b>FreeCodeCamp/Wiki</b></a></kbd></p>

> ----

**Pull request closed without merging**
