### PR TITLE
Added links to all screenhero alternatives

### PR DESCRIPTION
**Pull request by theflametrooper**
Pretty self explanatory..

### CODE REVIEW

**Comment by alayek** [comment]
Also add [Floobits](https://floobits.com/) to the list.

---
# LGTM :+1:

**Comment by Rafase282** [comment]
# LGTM 2

**Comment by abhisekp** [comment]
**Need File name Modification:-**
```diff
- How-to-install-Screenhero.md
+ How-To-Install-Screenhero.md
```

**Comment by theflametrooper** [comment]
Sorry, having a weird bug where you can't change capitalization and it be counted as a file change with git.

**Pull request merged**
