### PR TITLE
JavaScript Clean Up

### LINKED ISSUE #1144: Javascript articles tidy-up
**What needs changed:**

- [x] There is no main "Javascript.md" article.
- [x] We need to convert the remaining "Javascript-" articles to "JS-".

I'll get this implemented today. I'll also generally check filenames and consistency between articles.

### PR DESCRIPTION
**Pull request by atjonathan**
closes #1144

### CODE REVIEW

**Comment by Rafase282** [comment]
I'm on mobile right now but keep in mind existing links, if you can do a search project wise with atom for links with the old filenames. I use atom but other advance text editors should have something similar too.

**Comment by atjonathan** [comment]
@Rafase282, I checked that :heart_decoration:

**Comment by Rafase282** [comment]
I found links for the while loops.

**Comment by atjonathan** [comment]
@Rafase282, there you go :stuck_out_tongue_winking_eye:

**Pull request merged**
