### PR TITLE
Articles Starting with B: Rename filenames, add titles

### PR DESCRIPTION
**Pull request by Rafase282**
Refers #889
Closes #904

### CODE REVIEW

**Comment by theflametrooper** [comment]
Duplicate of #904?

**Comment by Rafase282** [comment]
Yes, I made my own, initially because I forgot there was one but I left it because it has changes that yours doesn't yet.

**Comment by theflametrooper** [comment]
@Rafase282 Do you want do close mine then?

**Comment by Rafase282** [comment]
I just finished making the updates on this one. So yes, you can merge this one and close yours.

**Pull request merged**
