### PR TITLE
Fix Wiki Labels for gitter chat

### PR DESCRIPTION
**Pull request by abhisekp**
This fixes bot response in gitter by lessening the number of characters i.e. 
gitter message character limit: `4096` :x: 
bot response characters: `2762` :white_check_mark: 

----
> **NOTE:** The link to [**Maintainer's Guide**]() and [**Review Board**]() are coming soon. 

----
> **Things to Check**
- Check all the links
- Check if the labels images load properly
- Check if the tooltip on hover over labels images show correctly
- See if the sentences are grammatically correct.

----
### In chat, this will appear like the following
Yep! This is now 100% @camperbot compatible. :alien: 

----

# Wiki Labels Guide
Labels help in categorizing [**issues**](https://github.com/FreeCodeCamp/wiki/issues) and [**pull requests**](https://github.com/FreeCodeCamp/wiki/pulls). Use **_issue_ only** labels for issues and **_PR_ only** labels for pull requests. Listed here are labels for [**FreeCodeCamp Wiki**](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki) &mdash; see [*wiki source*](https://github.com/FreeCodeCamp/wiki) and [*wiki labels*](https://github.com/FreeCodeCamp/wiki/labels).  

[**Label: QA**](#label-qa) [**Label: help wanted**](#label-help-wanted) [**Label: content update**](#label-content-update) [**Label: enhancement**](#label-enhancement) [**Label: WORK NEEDED:**](#label-work-needed) [**Label: LANG:**](#label-lang)  
[**Label: in progress**](#label-in-progress) [**Label: Translation**](#label-translation) [**Label: bug**](#label-bug) [**Label: blocked**](#label-blocked) [**Label: question**](#label-question) [**Label: invalid**](#label-invalid) [**Label: duplicate**](#label-duplicate)  
> *Click on individual labels to see detailed info*

See also: :whale: [**Label Overview**](#label-overview) **|** :dolphin: [**Label Details**](#label--detailed-description-and-usage) **|** :family: [Wiki Maintainer Guide](Wiki-Maintainer-Guide) **|** :cop: [Wiki Review Board](Wiki-Review-Board)

### CODE REVIEW

**Comment by abhisekp** [comment]
@FreeCodeCamp/wiki-mods Please review this completely.

**Comment by Rafase282** [comment]
# LGTM

Any concerns were already addressed in the wiki chat.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @abhisekp 

Lets :shipit: !

**Comment by alayek** [comment]
---
# LGTM :+1: 
---

**Comment by abhisekp** [comment]
Thanks @Rafase282, @raisedadead and @alayek for reviewing. :sparkles:

**Pull request merged**
