### PR TITLE
Title-case-a-sentence algorithm solution using Array.prototype.map()

### PR DESCRIPTION
**Pull request by ksharifbd**
It's added as a Fourth solution to the problem in `Algorithm-Title-Case-a-Sentence.md` file.

### CODE REVIEW

**Comment by Rafase282** [comment]
Please check the conflicts.

**Comment by ksharifbd** [comment]
Conflict solved. I'm confused as to labeling the solution i.e 'Sixth'. Should I write an explanation for it or existing explanations are sufficient?

**Comment by Rafase282** [comment]
Conflicts are still there, and always write explanation to each solution.

**Comment by ksharifbd** [comment]
Just've pushed my changes now. I added it as a second solution with a brief explanation. Please review.

**Comment by Rafase282** [comment]
I'll have to ask you to squash the commit, please.

**Comment by ksharifbd** [comment]
Just've squashed. Please review.

**Pull request merged**
