### PR TITLE
Text proofing

### PR DESCRIPTION
**Pull request by hallaathrad**
Minor style changes and typos.

### CODE REVIEW

**Comment by Rafase282** [comment]
Looks good to me. Thanks!

**Comment by Rafase282** [comment]
@hallaathrad could you please mention that only the first letter of every word must be capitalized for the filename?

**Comment by SaintPeter** [comment]
This is refereed to as 'Title Case'.  Words such as "and" "an" and "the" are not capitalized in title case.

**Comment by raisedadead** [comment]
@hallaathrad Please add a line like below:

> REMOVE THIS TEMPLATE TEXT FROM THE DESCRIPTION BEFORE YOU SUBMIT

Many contributors are just leaving this template in the PR description.

**Comment by Rafase282** [comment]
@SaintPeter yes I know but I wanted to make it easier for regex usage to find filenames that needs to be changed. Also I think filenames should be short, they are to be used in links and people using the search function will use keywords so while I'm not going as far as to ask not to use articles on filenames, the less the better.

Overall the aim is a short yet self descriptive filename/title with the title having more flexibility.

**Comment by Rafase282** [comment]
Thanks for the changes.

**Comment by raisedadead** [comment]
:+1: lets merge this

**Comment by hallaathrad** [comment]
Will squash in 20. Thanks for your patience

**Pull request merged**
