### PR TITLE
Forum

### PR DESCRIPTION
**Pull request by Rafase282**
My current progress on the migration

### CODE REVIEW

**Comment by Rafase282** [comment]
I think the conflict is due to the new articles that were not here.

**Comment by Rafase282** [comment]
Done

**Comment by atjonathan** [comment]
@Rafase282, let's work on this new branch instead of the one on your fork.

**Comment by Rafase282** [comment]
Alright, just make sure to check if the name is linked anywhere else and and if it is, to change the links with the full link of the forum post, the good thing is that even if the title change, the link will still work so we don't have to worry about links after they are set, they will always point tot he right article

**Comment by Rafase282** [comment]
# New Changes:

#1210

**Comment by Rafase282** [comment]
Well is no much reviewing as to it is to let everyone know the new changes. I used this because the conversation was locked and it was the first so I was thinking of having this as the center but perhaps I'll just make an issue instead.

**Pull request merged**
