### PR TITLE
Add declarative solution

### PR DESCRIPTION
**Pull request by hallaathrad**
I'm sure the explanation can be written more clearly but eloquence isn't my forte either. 
Help, anyone?

### CODE REVIEW

**Comment by Rafase282** [comment]
@hallaathrad You should put the solutions together and explanations together.

**Comment by hallaathrad** [comment]
Roger. Will fix and repost.

**Comment by hallaathrad** [comment]
Better? :) @Rafase282

**Comment by Rafase282** [comment]
Looks better, just debating whether to have you make some changes I noticed like removing or merging very similar solutions and numerate the code solutions.

**Comment by hallaathrad** [comment]
Of course. I'll change and let you merge before, so I can get the hang of it, and eventually be able to merge myself ;)

**Comment by Rafase282** [comment]
@hallaathrad thanks, let me know when is done and I'll merge.

**Comment by hallaathrad** [comment]
For a second I had understood you'd considered for me to do this throughout the different bonfires, etc. not just this one.  haha

Anyway, is this somehow what you had in mind?

**Comment by Rafase282** [comment]
Well I was asking for this one, if you want to do them for all the others that would be great too but it would be too much for me to ask.

**Comment by hallaathrad** [comment]
No need to ask :) I'd love to. If you like the way I did this one, I'll
move onto the rest like that. You can give me merge for those if you want
to take some load off for the future.

**Comment by Rafase282** [comment]
I don't think I can give you that access but I check pull request all the time as I get notifications via email. So accepting them or commenting them is not big deal. The issue is going through all the files on the wiki to check what needs to be changed and so, which means most of the time I just correct as I discover them. If you can do what you did with other pages that will be a big help for us all.

**Comment by hallaathrad** [comment]
Fo sho! I'll get on it asap. Any priority or unexpected start point?

**Comment by Rafase282** [comment]
Nope, you could start on the bonfires by level if you have the time, that should be easier for you to track.

**Pull request merged**
