### PR TITLE
Create a recursion explanation for beginners

### PR DESCRIPTION
**Pull request by MurrayBakerWebDeveloper**
# FreeCodeCamp - Wiki Pull Request Template
Make sure your contribution addresses the points mentioned below:

**Filenames:**
- Your filename should NOT contain any special characters or spaces.
- Use only `-` to separate words in the filename.
- Filenames should have the `.md` extension.
- Filenames should follow a Camel-Case format such as : `Title-For-The-Article.md`

**Formatting:**

Ensure that you use markdown syntax for articles, we do not accept `HTML` or `CSS` or anything else other than markdown. **Please Checkout these guides for reference:**
- [Master Markdown](https://guides.github.com/features/mastering-markdown/)
- [Working with Advanced Formatting](https://help.github.com/articles/working-with-advanced-formatting/)

**Commits and Squashing:**
- Your Pull Request/Submission should have only one commit.
- For multiple commits follow the [guide to squash them](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one)
- If you are new to contributing then you can [use the browser](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Guide-Online-Contribution), and we will squash multiple commits for you if requested.
- However, for more control over the pull request we recommend that you [use the local method](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-To-Contribute-To-The-Wiki) and request you to squash the commits yourself.

**Signing off:**
- If we merge your pull request, your name will be automatically added to the
- document history on GitHub, and the repo's contributors.
- Please don't add additional bylines when creating or editing an article.

Put `closes #XXXX` in your comment to auto-close the issue (if applicable),  only if your Pull Request is addressing the issue COMPLETELY, else just leave  a comment on the original issue with the Pull Request number.

### CODE REVIEW

**Comment by Rafase282** [comment]
Please read the description on this pull request and follow the instructions. The filename is not acceptable and please use Markdown.

**Comment by MurrayBakerWebDeveloper** [comment]
I read all i needed to do was make the name with dashes and that the .md makes the file in markdown format. What am I doing wrong?

**Comment by Rafase282** [comment]
The filename should be similar to this `Title-For-The-Article.md` and use markdown for styling, headers, links, etc.

**Comment by raisedadead** [comment]
@MurrayBakerWebDeveloper  

- This article needs to be formatted properly for readability before being accepted. 

- Please look at the [markdown guide](https://guides.github.com/features/mastering-markdown/) and use headings, quotes as necessary.

- Also I recommend you cite some examples in the article instead off pointing to external sources.

**Comment by MurrayBakerWebDeveloper** [comment]
Ok give me a week to find the time and I'll make it happen.

**Comment by Rafase282** [comment]
@MurrayBakerWebDeveloper I will close this PR, when you are ready just check to make sure no one has made something similar and create the new one with the changes. Even after it is closed you can still reference it and look at it for the suggestions.

**Pull request closed without merging**
