### PR TITLE
Update Algorithm Symmetric Difference

### PR DESCRIPTION
**Pull request by dakshshah96**
Refer #1094 
- Removed one of the solutions (https://repl.it/CLod/0) because it wasn't working.
- Added a new Basic solution.

### CODE REVIEW

**Comment by Rafase282** [comment]
The intermediate solution is mine, if you added the basic then you can add your name, which means we can remove the other names.

Also https://repl.it/CLod/0 works so we don't need to remove this solution.

**Comment by dakshshah96** [comment]
Can you provide the explanation for https://repl.it/CLod/0 ?
And about the names, if we include  https://repl.it/CLod/0, which names should I keep?

**Comment by Rafase282** [comment]
Names to keep:

- @Rafase282
- @imranismail
Yours if you still add the solution. 

The others can be removed.

**Comment by Rafase282** [comment]
Links for the ES6 solution:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator
map, reduce and filter we should have on FCC.

**Comment by atjonathan** [comment]
### **LGTM :+1:**

**Pull request merged**
